services:
  db-demo-1:
    image: postgres:13.15
    restart: unless-stopped
    env_file:
      - .env
    #ports:
    #  - 127.0.0.1:5433:5432
    #ports:
    #  - "5432:5432"
    expose:
      - "5432"
    volumes:
      - db-data-demo-1-0:/var/lib/postgresql/data
    networks:
      - dokploy-network

  hr-tools-backend-demo-1:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    #container_name: hr-tools-backend
    depends_on:
      - db-demo-1
      - minio-demo-1
    #ports:
    #  - 8080:8080
    expose:
      - "8080"
      #- "30128:8080"
    networks:
      - dokploy-network
  minio-demo-1:
    restart: unless-stopped
    image: docker.io/bitnami/minio:2024.11.7
    #ports:
    #  - 9001:9001
    expose:
      - "9000"
      - "9001"
    volumes:
      - 'minio_data:/bitnami/minio/data'
    env_file:
      - .env
    networks:
      - dokploy-network

  # nginx:
  #   image: nginx:latest
  #   restart: unless-stopped
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   depends_on:
  #     - hr-tools-backend
  #   volumes:
  #     - ./config/nginx.conf:/etc/nginx/nginx.conf
  #     - /etc/letsencrypt/archive/:/etc/letsencrypt/archive/
  #   networks:
  #     - backend
  
  # Через докер лучше не запускать, тк время обработки увеличивается многократно
  # ollama:
  #   image: ollama/ollama:latest
  #   container_name: ollama
  #   ports:
  #     - "11434:11434"
  #   volumes:
  #     - ollama_data:/root/.ollama
  #   environment:
  #     - OLLAMA_HOST=0.0.0.0:11434
  #   platform: linux/arm64
  #   restart: unless-stopped
  #   # загрузка моделей
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5
      
  # ollama-setup:
  #   image: ollama/ollama:latest
  #   depends_on:
  #     ollama:
  #       condition: service_healthy
  #   volumes:
  #     - ollama_data:/root/.ollama
  #   command: >
  #     sh -c "sleep 10 &&
  #            ollama pull deepseek-r1:8b &&
  #            echo 'Модели загружены успешно'"
  #   restart: "no"

networks:
  dokploy-network:
    external: true

volumes:
  db-data-demo-1-0: {}
  minio_data: {}
  # ollama_data: